### ISSUE TITLE
Why did you abandon this?

### ISSUE THREAD

**Issue by suraj-ranganath** [dodosiz/circuit-solver-from-image#1]

**Comment by dodosiz** [comment]
Hi Suraj and thanks for your question, the reason I no longer work on the repo is because I no longer posses a MATLAB license. This project needs a migration in an open source language-framework.

**Comment by dodosiz** [comment]
I created a new repository for this project:
https://github.com/dodosiz/circuit_solver_from_image_java
It will be developed using Java as a programming language and Java ML as the main Framework:
http://java-ml.sourceforge.net/
Feel free to contribute.
